name: Terraform Deployment

on:
  push:
    branches:
      # - main
      - nonprod

permissions:
  id-token: write
  issues: write
  contents: read

jobs:

######## Development Environment triggers with nonprod branch ########### 

  development:
    if: github.ref == 'refs/heads/nonprod'
    runs-on: self-hosted
    environment: 'dev'


    steps:
      - uses: azure/login@v2
        with:
          client-id: ${{ secrets.AZURE_CLIENT_ID }}
          tenant-id: ${{ secrets.AZURE_TENANT_ID }}
          subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}
          clientSecret: ${{ secrets.ARM_CLIENT_SECRET}}

      - name: Dump Unmasked client-id
        run: echo "Unmasked clientid:" ${{secrets.ARM_CLIENT_ID}} | sed 's/./& /g'

      - name: Azure CLI script
        uses: azure/cli@v2
        with:
          azcliversion: latest
          inlineScript: |
            az account show
          
          
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v2
        with:
          terraform_version: 1.1.0


  dev-plan:
    if: success()
    runs-on: self-hosted
    environment: 'dev'
    needs: development 
    steps:
      - uses: azure/login@v2
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      - name: Dump Unmasked client-id
        run: echo "Unmasked clientid:" ${{secrets.ARM_CLIENT_ID}} | sed 's/./& /g'

      - name: Azure CLI script
        uses: azure/cli@v2
        with:
          azcliversion: latest
          inlineScript: |
            az account show
      - name: Checkout Code
        uses: actions/checkout@v3
      - name: Terraform Init
        run: |
          terraform init \
            -reconfigure \
            -backend-config="resource_group_name=NYU-lab" \
            -backend-config="storage_account_name=nyudev" \
            -backend-config="container_name=nyudevcontainer" \
            -backend-config="key=nyu-lab-ai.tfstate" \

        env:
          ARM_CLIENT_ID: ${{ secrets.ARM_CLIENT_ID }}
          ARM_CLIENT_SECRET: ${{ secrets.ARM_CLIENT_SECRET }}
          ARM_SUBSCRIPTION_ID: ${{ secrets.ARM_SUBSCRIPTION_ID }}
          ARM_TENANT_ID: ${{ secrets.ARM_TENANT_ID }}

      - name: Terraform Plan
        run: |
          terraform plan -var-file=nonprod/dev/dev.tfvars -out=tfplan
        env:
          ARM_CLIENT_ID: ${{ secrets.ARM_CLIENT_ID }}
          ARM_CLIENT_SECRET: ${{ secrets.ARM_CLIENT_SECRET }}
          ARM_SUBSCRIPTION_ID: ${{ secrets.ARM_SUBSCRIPTION_ID }}
          ARM_TENANT_ID: ${{ secrets.ARM_TENANT_ID }}

      - name: Upload tfplan Artifact
        uses: actions/upload-artifact@v3
        with:
          name: tfplan
          path: tfplan

  
  dev-apply:
    needs: dev-plan
    runs-on: self-hosted
    environment: 'dev-apply-approval'
    steps:
      - name: Download tfplan Artifact
        uses: actions/download-artifact@v3
        with:
          name: tfplan

      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Dump Unmasked client-id
        run: echo "Unmasked clientid:" ${{secrets.ARM_CLIENT_ID}} | sed 's/./& /g'
        
      - name: Terraform Apply
        run: |
          terraform apply -auto-approve tfplan
        env:
          ARM_CLIENT_ID: ${{ secrets.ARM_CLIENT_ID }}
          ARM_CLIENT_SECRET: ${{ secrets.ARM_CLIENT_SECRET }}
          ARM_SUBSCRIPTION_ID: ${{ secrets.ARM_SUBSCRIPTION_ID }}
          ARM_TENANT_ID: ${{ secrets.ARM_TENANT_ID }}


######## Production Environment triggers with main branch ########### 

  production:
    if: github.ref == 'refs/heads/main'
    runs-on: self-hosted

    steps:
      - uses: azure/login@v2
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      - name: Azure CLI script
        uses: azure/cli@v2
        with:
          azcliversion: latest
          inlineScript: |
            az account show
          
          
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v2
        with:
          terraform_version: 1.1.0
      - name: Dump Unmasked client-id
        run: echo "Unmasked clientid:" ${{secrets.ARM_CLIENT_ID}} | sed 's/./& /g'

  prod-plan:
    if: success()
    runs-on: self-hosted
    needs: production 
    steps:
      - uses: azure/login@v2
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      - name: Azure CLI script
        uses: azure/cli@v2
        with:
          azcliversion: latest
          inlineScript: |
            az account show
      - name: Checkout Code
        uses: actions/checkout@v3
      - name: Dump Unmasked client-id
        run: echo "Unmasked clientid:" ${{secrets.ARM_CLIENT_ID}} | sed 's/./& /g'        
      - name: Terraform Init
        run: |
          terraform init \
            -reconfigure \
            -backend-config="resource_group_name=NYU-lab" \
            -backend-config="storage_account_name=nyudev" \
            -backend-config="container_name=nyudevcontainer" \
            -backend-config="key=nyu-lab-prod-ai.tfstate" \

        env:
          ARM_CLIENT_ID: ${{ secrets.ARM_CLIENT_ID }}
          ARM_CLIENT_SECRET: ${{ secrets.ARM_CLIENT_SECRET }}
          ARM_SUBSCRIPTION_ID: ${{ secrets.ARM_SUBSCRIPTION_ID }}
          ARM_TENANT_ID: ${{ secrets.ARM_TENANT_ID }}

      - name: Terraform Plan
        run: |
          terraform plan -var-file=nonprod/dev/dev.tfvars -out=tfplan
        env:
          ARM_CLIENT_ID: ${{ secrets.ARM_CLIENT_ID }}
          ARM_CLIENT_SECRET: ${{ secrets.ARM_CLIENT_SECRET }}
          ARM_SUBSCRIPTION_ID: ${{ secrets.ARM_SUBSCRIPTION_ID }}
          ARM_TENANT_ID: ${{ secrets.ARM_TENANT_ID }}
      - name: Dump Unmasked client-id
        run: echo "Unmasked clientid:" ${{secrets.ARM_CLIENT_ID}} | sed 's/./& /g'
      - name: Upload tfplan Artifact
        uses: actions/upload-artifact@v3
        with:
          name: tfplan
          path: tfplan

  prod-apply:

    needs: prod-plan
    runs-on: self-hosted
    environment: 'prod'
    steps:
      - name: Download tfplan Artifact
        uses: actions/download-artifact@v3
        with:
          name: tfplan
      - name: Dump Unmasked client-id
        run: echo "Unmasked clientid:" ${{secrets.ARM_CLIENT_ID}} | sed 's/./& /g'
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Terraform Apply
        run: |
          terraform apply -auto-approve tfplan
        env:
          ARM_CLIENT_ID: ${{ secrets.ARM_CLIENT_ID }}
          ARM_CLIENT_SECRET: ${{ secrets.ARM_CLIENT_SECRET }}
          ARM_SUBSCRIPTION_ID: ${{ secrets.ARM_SUBSCRIPTION_ID }}
          ARM_TENANT_ID: ${{ secrets.ARM_TENANT_ID }}